{% set name = "gevent" %}
{% set version = "20.9.0" %}
{% set sha256 = "5f6d48051d336561ec08995431ee4d265ac723a64bba99cc58c3eb1a4d4f5c8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:   # [unix]
    - 0001-Allow-include-flags-to-be-present-in-CFLAGS.patch        # [unix]
    - 0002-Allow-library-flags-to-be-present-in-LDFLAGS.patch       # [unix]
    - 0003-Do-not-use-hard-coded-path-for-file-command.patch        # [unix]
    - 0004-Allow-macro-to-be-present-in-CFLAGS.patch                # [unix]
    - 0005-Drop-isysroot-if-CONDA_BUILD_SYSROOT-is-specified.patch  # [unix]

build:
  number: 1
  script:
    - copy %SRC_DIR%\deps\c-ares\ares_build.h.dist %SRC_DIR%\deps\c-ares\ares_build.h  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - libmagic  # [unix]
    - make      # [unix]

  host:
    # cffi 1.4.0 is the general minimum version
    # With Python 3 version 1.11.3 is minimum
    # On windows 1.11.5 is the minimum
    # Rather than special casing each of these use a single minimum version
    - cffi >=1.11.5
    - pip
    - python

  run:
    - cffi >=1.11.5
    - python
    - greenlet >=0.4.17
    - zope.event
    - zope.interface
    - setuptools

test:
  requires:
    - pip
  imports:
    - gevent
    - gevent.libev
  commands:
    - python -m pip check

about:
  home: https://www.gevent.org
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - deps/libuv/LICENSE
    - deps/libev/LICENSE
    - deps/c-ares/LICENSE.md
  summary: Coroutine-based network library
  description: |
    Gevent uses greenlet to provide a high-level synchronous API on top of the libev event loop.
  doc_url: https://www.gevent.org/contents.html
  dev_url: https://github.com/gevent/gevent

extra:
  recipe-maintainers:
    - nehaljwani
