{% set name = "gevent" %}
{% set version = "1.3.2" %}
{% set sha256 = "390d820f375626cd0406fdf9b2657f796818fa53c7cff34a9af0e34a4d6bc4ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython
    - cffi >=1.3.0  # [not win]
    - python
    - setuptools

  run:
    - cffi >=1.3.0  # [not win]
    - python
    - greenlet >=0.4.10

test:
  imports:
    - gevent
    - gevent.libev

about:
  home: http://www.gevent.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Coroutine-based network library'
  description: |
    Gevent uses greenlet to provide a high-level synchronous API on top of the libev event loop.
  doc_url: http://www.gevent.org/contents.html
  dev_url: https://github.com/gevent/gevent

extra:
  recipe-maintainers:
    - nehaljwani
