{% set name = "gevent" %}
{% set version = "25.4.2" %}
{% set sha256 = "7ffba461458ed28a85a01285ea0e0dc14f883204d17ce5ed82fa839a9d620028" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - export GEVENTSETUP_EMBED=0  # [unix]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi >=1.17.1                          # [build_platform != target_platform]
    - cython >=3.0.11                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make      # [unix]

  host:
    - cffi >=1.17.1
    - cython >=3.0.11
    - pip
    - setuptools >=40.8.0
    - greenlet >=3.0.3
    - python
    - libev     # [unix]
    - libuv     # [unix]
    - c-ares    # [unix]

  run:
    - cffi >=1.17.1
    - python
    - greenlet >=3.1.1
    - zope.event
    - zope.interface
    - setuptools

test:
  requires:
    - pip
  imports:
    - gevent
    - gevent.libev
    - gevent.libuv
    - gevent.resolver
  commands:
    - python -m pip check
    - python -m gevent.tests test__util.py test__monkey.py test__thread.py

about:
  home: https://www.gevent.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Coroutine-based network library
  description: |
    Gevent uses greenlet to provide a high-level synchronous API on top of the libev event loop.
  doc_url: https://www.gevent.org/contents.html
  dev_url: https://github.com/gevent/gevent

extra:
  recipe-maintainers:
    - beenje
    - nehaljwani
