appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: myXRCZFC8hukPVhAVhQubT9fC866mfXWXgNHUJkPGCOctKhkXOgV2taEIy76fvJecyB+W5OUfUvQiw4oUmsELCvGfAu2Waahs5GzvA6+j9AOOc+d9jKdW/Ji9gFNjQDz+vGuc8wW6mOCyrwsDJCqF5czv32S5AXCu7P7VUIAJ442EjV3hu/KibBWGSsUpgw8mWLDaPWR7qsKlyEVrD8bhubVsx16ZJqgDUVWpU0DW7X10z6bBZKcpO0x97mLLKxVsTyNJ5sOOAHCALjdKX4F14E/l7Dmrt7RQ/RcJTXy68XNP1RWXwPiDzUNtV2qHKosJZwS+7DRw2oHv8AwaHwSxkz3ST53dNM2aP5xj8MNmzRS2oBnAmGUTig32zNoiv3CmzDB8Z7PPHOR8c6eIt7/sFrxfrkuGNH6DSFR9puH2YfOvOvb5RJkd8Yy9qY4ljO2IYAPaBXTBDO8IZS20ZjMaafi1cJ8biBCOq9Z2APkMgi62OMVY04eC+XzgSDKrVisl8amo34YmzU6rbDaqcS1rE3dYfqF89z+D97U+UxUzGLVr3AKup5wziQ74LeXwLUdEnpZyL6M9Qe7PBg0+vIjXMXtrSqlffwnncf6ndIdx+sj1CxQ4R5q0PI0f/toiWSmNfMPZzYFFIaaQz7peF8yc0DOvp8VDvUYNuYca7EQXX0=}
